### ISSUE TITLE
"Read More" button on main page is not clickable (desktop and mobile)

### ISSUE THREAD

**Issue by nathanielcompton** [cupofdata/www-site#103]
I cannot press the "Read More" button on either the desktop or mobile versions of the site.

![screen shot 2018-02-15 at 11 32 19 am](https://user-images.githubusercontent.com/12648281/36268229-fdced532-1243-11e8-9849-efed3a520118.png)

**Comment by Goolzzi** [comment]
@jgwerner what is your desire action when click this button? Maybe... It could be `/blog`? Am I correct?

/cc @nathanielcompton

**Comment by jgwerner** [comment]
@Goolzzi yes, that works for now. Ideally, the `Read more` option for the article itself would point to the article itself, instead of the master blog page. But I don't know if that is feasible right now. It would have to be that way eventually, otherwise the user would have to search for the news item again in the blog page.

**Comment by Goolzzi** [comment]
@jgwerner Absolutely, it will be feasible if I have done integrating cms in this part.
Btw, every article will have `Read more` button and it will be different with the design.
What do you think?

**Comment by jgwerner** [comment]
Yes, I think that is a good option. Either every article could have a read more button or read more link. This would allow us to fix the first lines to (n) number which would make the layout consistent, regardless of the article's length.
